#!/bin/zsh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bsp or float (default: bsp)
yabai -m config layout bsp
yabai -m config external_bar all:30:0

YABAI_PADDING=5
yabai -m config top_padding $YABAI_PADDING
yabai -m config bottom_padding $YABAI_PADDING
yabai -m config left_padding $YABAI_PADDING
yabai -m config right_padding $YABAI_PADDING

yabai -m config window_gap $YABAI_PADDING

# float system preferences. Most of these just disable Yabai from resizing them.
source $HOME/.config/yabai/yabai-float-apps.sh

# Arc Browser specific
# yabai -m rule --add app="^Arc$" title="^$" mouse_follows_focus=off

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

## Some random global settings
# yabai -m config focus_follows_mouse          autoraise
# yabai -m config focus_follows_mouse          on

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

## WTIH SIP DISABLED (Limelight build into Yabai, enable it here)
yabai -m config window_border on
yabai -m config window_border_width 1

# yabai -m config active_window_border_color 0xFF40FF00
# FFAF00
# yabai -m config active_window_border_color 0xff50fa7b # green
# yabai -m config active_window_border_color 0xffFFAF00 # orange
#
# note: yabai 5.0 border color options
# yabai -m config active_window_border_color 0xff8BE9FD # cyan
# yabai -m config normal_window_border_color 0x00FFFFFF
# yabai -m config insert_feedback_color        0xffd75f5f

## some other settings
yabai -m config auto_balance off
yabai -m config split_ratio 0.50

# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

borders active_color=0xff8BE9FD inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
